version: '3'

services:
  api:
    container_name: go-shop-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    container_name: go-shop-db
    image: postgres:14.2
    volumes:
      - ./docker/data/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=go-shop
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop1234
      - POSTGRES_HOST=go-shop-postgres
    ports:
      - "5432:5432"

